name: Build Release

on:
  workflow_dispatch: # 允许手动触发执行

jobs:
  build:
    name: Build APK and Windows
    runs-on: windows-latest # 使用 Windows 虚拟机，可以同时编译 Android 和 Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/runner/Release/
